#!/bin/bash
# Generates GeneratedConfig.swift from environment variables.
# Run as a pre-compile Xcode build phase.
# Required env vars: AZURE_STORAGE_ACCOUNT, AZURE_STORAGE_KEY, AZURE_CONTAINER_NAME

set -euo pipefail

OUTPUT="${SRCROOT}/GeneratedConfig.swift"

if [ -z "${AZURE_STORAGE_ACCOUNT:-}" ] || [ -z "${AZURE_STORAGE_KEY:-}" ] || [ -z "${AZURE_CONTAINER_NAME:-}" ]; then
    echo "warning: Azure environment variables not set. Using empty defaults."
    AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:-}"
    AZURE_STORAGE_KEY="${AZURE_STORAGE_KEY:-}"
    AZURE_CONTAINER_NAME="${AZURE_CONTAINER_NAME:-mactodo}"
fi

cat > "$OUTPUT" << EOF
// AUTO-GENERATED — DO NOT EDIT
// Generated by Scripts/generate-config.sh
enum GeneratedAzureConfig {
    static let storageAccount = "${AZURE_STORAGE_ACCOUNT}"
    static let storageKey = "${AZURE_STORAGE_KEY}"
    static let containerName = "${AZURE_CONTAINER_NAME}"
}
EOF

echo "Generated $OUTPUT"
